async_aws:
    clients:
        s3:
            type: s3
            config:
                region: '%env(AWS_REGION)%'
                accessKeyId: '%env(AWS_ACCESS_KEY_ID)%'
                accessKeySecret: '%env(AWS_SECRET_ACCESS_KEY)%'
